
ALTER TABLE release ALTER COLUMN downloads TYPE BIGINT;
ALTER TABLE release ALTER COLUMN uploaded_at TYPE BIGINT;
ALTER TABLE application ALTER COLUMN uploaded_at TYPE BIGINT;
ALTER TABLE package ALTER COLUMN uploaded_at TYPE BIGINT;
ALTER TABLE package ALTER COLUMN filesize TYPE BIGINT;
